# Generated by Django 4.2.23 on 2026-06-04 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmarks', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='exercises.exercise'),
        ),
    ]
