# Generated by Django 4.2.23 on 2026-06-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='exercise_videos/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_thumbnails/'),
        ),
    ]
